cli:   "bitrot-scanner"
group: "root"
user:  "root"

targets:
#  centos-6:
#    default_dependencies: false
#    build_dependencies:
#      # required for go buildpack
#      - perl-Digest-SHA
  centos-7:
    default_dependencies: false
    build_dependencies:
      # required for go buildpack
      - perl-Digest-SHA
  debian-7:
    default_dependencies: false
  debian-8:
    default_dependencies: false
  sles-11:
    default_dependencies: false
  sles-12:
    default_dependencies: false
  ubuntu-12.04:
    default_dependencies: false
  ubuntu-14.04:
    default_dependencies: false
  ubuntu-16.04:
    default_dependencies: false
  ubuntu-18.04:
    default_dependencies: false

before:
  - sed -i'' s/__BITROT_SCANNER_VERSION__/$(git describe --tags)/ version.go

after:
  - rm -rvf Godeps vendor *.go .profile.d Makefile

buildpack: https://github.com/kr/heroku-buildpack-go.git
