cli:   "bitrot-scanner"
group: "root"
user:  "root"

targets:
#  centos-6:
#    build_dependencies:
#      # required for go buildpack
#      - perl-Digest-SHA
  centos-7:
    build_dependencies:
      # required for go buildpack
      - perl-Digest-SHA
  debian-7:
  debian-8:
  sles-11:
  sles-12:
  ubuntu-12.04:
  ubuntu-14.04:
  ubuntu-16.04:
  ubuntu-18.04:

before:
  - sed -i'' s/__BITROT_SCANNER_VERSION__/$(git describe --tags)/ version.go

after:
  - rm -rvf Godeps vendor *.go .profile.d Makefile

buildpack: https://github.com/kr/heroku-buildpack-go.git
